### ISSUE TITLE
fall through on errors

### ISSUE THREAD

**Issue by jay-at-avido** [joshuaslate/mern-starter#10]
I was having some problems with code executing beyond what it should when an error happened, but I can no longer pinpoint where that was for sure, probably in the forgotPassword middleware.

It looks to me that there's some inconsistence on how you handle the way you call next, sometime you just call next() , sometimes you call "return next()" ?

You can compare with my version of the same function:  http://pastie.org/10970014

**Comment by joshuaslate** [comment]
Thanks for pointing that out. Please let me know what that issue is if you keep having it after pulling the latest. I just pushed some changes that improve consistency with returns.
