### ISSUE TITLE
requireOwner and requireAdmin middleware is missing

### ISSUE THREAD

**Issue by jay-at-avido** [joshuaslate/mern-starter#11]
What the title says.

**Comment by joshuaslate** [comment]
My most recent commit should address this. The middleware can pretty easily be altered to meet your needs.

**Comment by jay-at-avido** [comment]
Ouch... have you recently changed most/all  server modules to use imports instead of requires !?!

I'm not using Babel in my workflow ( I dont develop frontend code)  so this will effectively kill this project for me. 

Talk about being out of luck :-(

**Comment by joshuaslate** [comment]
Are you using Node v6+ (the current LTS)? It should work, if so.

**Comment by jay-at-avido** [comment]
I can use the latest version, no problem.
Are you should, what is your source?
Acording to this document es6 module support it's still in draft  and I was also not able to find anything in Node.green

Let me know

**Comment by joshuaslate** [comment]
It is possible I am wrong. I just remember having an issue with using import syntax server-side on a project I was working on, and upgrading to Node v6 fixed that. I'm making a change back to require syntax, because it's probably safer.

**Comment by jay-at-avido** [comment]
This is the related topic regarding the V8 support for modules, which Node.js depends on.
I don't think it's fixed yet: 
https://bugs.chromium.org/p/v8/issues/detail?id=1569

**Comment by joshuaslate** [comment]
It looks like you're right. I just merged some changes that should work without adding Babel to the workflow.
