### ISSUE TITLE
/dashboard/inbox throws Uncaught ReferenceError: api_url is not defined

### ISSUE THREAD

**Issue by Thundechile** [joshuaslate/mern-starter#2]
The server seems to work ok and I can also login with client.

However if I navigate to http://localhost:8080/dashboard/inbox (from Inbox link) then the page shows no conversations and in browser console I've got the error:
Uncaught ReferenceError: api_url is not defined

In the database I have role "Admin" for the user that throws the error (haven't tried other role values yet).
Is the problem somewhere in my configuration or is there a bug in the code?

**Comment by joshuaslate** [comment]
This should now be fixed. I had a typo. Pull the latest. Thank you for catching this!

**Comment by Thundechile** [comment]
Thanks! That was fast and can confirm that it works now.

Thanks for the excellent repository and tutorials, have found your tutorials and code among the best that the web has to offer.

**Comment by joshuaslate** [comment]
Thanks, Thundechile, I appreciate the kind words!
