### ISSUE TITLE
Request for a build script

### ISSUE THREAD

**Issue by yarnball** [joshuaslate/mern-starter#21]
Hi,

This is a great boiler plate!

Was just wondering, could you please provide a build script for this. I'm new to react, and I'm not sure how this would work.

If it already has a built script- how do I run it? 

Thanks

**Comment by joshuaslate** [comment]
Hi Yarnball,

You should just be able to run `webpack` in order to build the app.

Thanks,

Josh

**Comment by yarnball** [comment]
Hi Josh,

Thanks- I mean to build a version ready for production. IE a build I can copy to my webserver. Using `npm start` only makes it run locally for me.
