### ISSUE TITLE
Social Auth Integration

### ISSUE THREAD

**Issue by tarkanlar** [joshuaslate/mern-starter#4]
Hey @joshuaslate, this library is really awesome for starting. I know it is a long term plan but what is your advice for starting doing Social Auth Integration?

**Comment by joshuaslate** [comment]
Hi @tarkanlar! Thank you! There are many passport strategies geared towards social authentication. Here's one for Facebook: https://github.com/jaredhanson/passport-facebook

I would say these would be great starting points. I do hope to get to this within the next few months. I've got a lot on my plate right now, but my fingers are crossed.

Thanks,

Josh
