### ISSUE TITLE
Do NOT return the raw User Entry

### ISSUE THREAD

**Issue by Stefflan00** [joshuaslate/mern-starter#5]
Just saw that you return basically the whole user entry. 
https://github.com/joshuaslate/mern-starter/blob/master/server/controllers/user.js#L16

I guess you want to use the same function as in the authentication controller.

```
// Set user info from request
function setUserInfo(request) {
  let getUserInfo = {
    _id: request._id,
    firstName: request.profile.firstName,
    lastName: request.profile.lastName,
    email: request.email,
    role: request.role,
  };

  return getUserInfo;
}
```

If so, where does it make sense to implement this function. 
Do you create a file "common/user.js" folder under the "controllers" directory?

Or does it actually make sense to use the "virtual" function of mongoose since in that case we anyways get the user from the DB.
in the User Model we would add:
```
UserSchema.virtual('info').get( function(){
  return {
    _id: this._id,
    firstName: this.profile.firstName,
    lastName: this.profile.lastName,
    email: this.email,
    role: this.role,
  }
});
```

and in the Controller:

```
res.status(200).json({ user: req.user.info});
```

And in the Authentication Controller we change that as well.

**Comment by joshuaslate** [comment]
I decided to just roll out a helpers.js file, where helper functions like an input validator could be added in the future.
