### ISSUE TITLE
/reset-password route should be a GET

### ISSUE THREAD

**Issue by jay-at-avido** [joshuaslate/mern-starter#7]
I think this line should be a .get() and not a .post():

`authRoutes.post('/reset-password/:token', AuthenticationController.verifyToken);`

**Comment by joshuaslate** [comment]
Why do you think that, out of curiosity? I think .post() or .put() are valid, because this controller verifies the token, then it updates the user's document.

**Comment by jay-at-avido** [comment]
Sorry, I'm using only the server part of the code but now I understand that you are linking to a static page that will call the API. 
Sorry for the trouble

**Comment by joshuaslate** [comment]
No worries! Thanks for taking a look at the project. If you see anything you think could be better, please send over a pull request.

**Comment by jay-at-avido** [comment]
Sure, will definitely have some feedback. Have only been messing with it for a few hours but it looks great so far.
Btw, if you want to add a config/sendgrid.js, here you go:  http://pastie.org/10968489

**Comment by joshuaslate** [comment]
Thanks, I got that added!
