### ISSUE TITLE
Nodemon 

### ISSUE THREAD

**Issue by gridworkz** [joshuaslate/mern-starter#9]
Hi Joshua:

Just a quickie. Nodemon needs to be added to server/packages.json. I always need to add it on fresh installs....BTW: thanks for the new update!

Cheers,
Dave

**Comment by joshuaslate** [comment]
Hi Dave,

Sorry, I just have it installed globally (npm install -g nodemon). I'll add this to the package.json file for convenience now. No problem on the other updates! I've got more to do, just no time to get to it all, as always :)

Best,

Josh
